analysis:
  timeframe: "1h"
  indicator: "bbw"

apis:
  coingecko:
    base_url: "https://api.coingecko.com/api/v3"
    rate_limit: 2

scan:
  pages: 4
  coins_per_page: 250

# Market Filtering (Easily Configurable)
market_filter:
  min_market_cap: 100000000       # 100M USD (adjustable)
  min_volume_24h: 10000000        # 10M USD (adjustable)

processing:
  batch_size: 50
  rate_limit_delay: 0.1

alerts:
  format: "enhanced_bbw"
  include_coinglass: true
  consolidate_signals: true
