# 30-Minute CipherB Alert System Configuration

cipherb:
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60

scan:
  pages: 2
  coins_per_page: 250
  rate_limit: 2

apis:
  coingecko:
    base_url: "https://api.coingecko.com/api/v3"
    rate_limit: 2
  bingx:
    rate_limit: 300
  kucoin:
    rate_limit: 500

alerts:
  telegram:
    max_message_length: 4000
    batch_size: 20
  freshness:
    window_minutes: 30  # 10 minutes for 30m timeframe

  # Market filtering thresholds (applied in data_fetcher.py)
market_filter:
  min_market_cap: 100000000   # 100M USD  
  min_volume_24h: 20000000    # 20M USD
  description: "Quality coins with established liquidity"
