analysis:
  timeframe: "1h"
  indicator: "bbw"
  bbw_params:
    length: 20
    multiplier: 2.0
    expansion_length: 125
    contraction_length: 125
    tolerance: 0.01

market_filter:
  min_market_cap: 50000000    # $50M USD minimum
  min_volume_24h: 10000000    # $10M USD minimum

processing:
  batch_size: 50
  rate_limit_delay: 0.1

alerts:
  format: "enhanced_bbw"
  include_coinglass: true
  consolidate_signals: true
