# Simple Config - Just the essentials
cipherb_config:
  filters:
    min_market_cap: 100000000    # $100M
    min_volume_24h: 10000000     # $10M

bbw_config:
  filters:
    min_market_cap: 100000000    # $100M
    min_volume_24h: 50000000     # $50M

ema_config:
  filters:
    min_market_cap: 10000000     # $10M
    min_volume_24h: 10000000     # $10M
