# BBW Multi-Timeframe Squeeze Detection System Configuration

bbw:
  length: 20
  multiplier: 2.0
  contraction_length: 125
  squeeze_tolerance: 0.01

timeframes:
  primary: "30m"
  secondary: "1h"

freshness_windows:
  "30m": 35  # minutes
  "1h": 65   # minutes

scan:
  pages: 5
  coins_per_page: 250
  rate_limit: 2

apis:
  coingecko:
    base_url: "https://api.coingecko.com/api/v3"
    rate_limit: 2
  bingx:
    rate_limit: 300
  kucoin:
    rate_limit: 500

alerts:
  telegram:
    max_message_length: 4000
    batch_size: 20

# Market filtering thresholds (unchanged - existing logic maintained)
market_filter:
  min_market_cap: 50000000  # 50M USD
  min_volume_24h: 10000000   # 10M USD
  description: "Quality coins with established liquidity"
