name: BBW 2H Analysis

on:
  schedule:
    - cron: '2 */2 * * *'  # Every 2 hours
  workflow_dispatch:

jobs:
  bbw-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    - name: Run BBW Analysis
      env:
        BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        BBW_TELEGRAM_CHAT_ID: ${{ secrets.BBW_TELEGRAM_CHAT_ID }}
      run: |
        echo "🔵 BBW 2H Analysis..."
        python src/analyzers/bbw_analyzer.py
