name: Daily Market Data Collection

on:
  schedule:
    - cron: '0 1 * * *'  # 06:30 IST daily
  workflow_dispatch:

jobs:
  fetch-unlimited-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Unlimited Data Fetcher
      env:
        COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
      run: |
        python src/data_fetcher.py --daily-scan
        
    - name: Commit updated cache
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cache/
        if ! git diff --staged --quiet; then
          git commit -m "Daily data update: $(date +'%Y-%m-%d %H:%M IST')"
          git push
        else
          echo "No changes to commit"
        fi
