name: Daily Data Collection

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    - name: Collect Market Data
      env:
        COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
      run: python src/data_fetcher.py
    - name: Commit datasets
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin main
        git add cache/*.json
        git diff --staged --quiet || (git commit -m "📊 Daily data update $(date '+%Y-%m-%d %H:%M')" && git push origin main)

    - name: Clean up
      if: always()
      run: |
        echo "🧹 Cleaning up temporary files..."
        find . -name "*.pyc" -delete || true
        find . -name "__pycache__" -type d -exec rm -rf {} + || true
        echo "✅ Cleanup complete"
