name: Daily Market Data Fetcher

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at 00:00 UTC
  workflow_dispatch:

jobs:
  fetch-market-data:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests PyYAML python-dateutil
    
    - name: Create cache directory
      run: mkdir -p cache
      
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
    - name: Fetch market data
      env:
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      run: |
        python src/data_fetcher.py --daily-scan
    
    - name: Save market data cache
      uses: actions/cache@v3
      with:
        path: cache/
        key: market-data-${{ steps.date.outputs.date }}
    
    - name: Log completion
      run: |
        echo "✅ Market data fetch completed"
        ls -la cache/
