name: "Enhanced High-Risk 15m CipherB + VWMA Analysis"

on:
  schedule:
    # Run every 15 minutes at :02, :17, :32, :47
    - cron: '2,17,32,47 * * * *'
  workflow_dispatch:

jobs:
  enhanced-analysis:
    runs-on: ubuntu-latest
    
    env:
      # CoinGecko API
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      
      # Exchange APIs
      BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
      BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
      
      # Two-Stage Telegram Channels
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      STAGE1_TELEGRAM_CHAT_ID: ${{ secrets.STAGE1_TELEGRAM_CHAT_ID }}  # Monitoring channel
      STAGE2_TELEGRAM_CHAT_ID: ${{ secrets.STAGE2_TELEGRAM_CHAT_ID }}  # Execution channel
      
      # Python Configuration
      PYTHONPATH: ${{ github.workspace }}/src
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create Cache Directories
        run: |
          mkdir -p cache
          mkdir -p logs
          
      - name: Step 1 - Fetch High-Risk Market Data
        run: |
          echo "🔄 Fetching high-risk market data..."
          python src/enhanced_data_fetcher.py
          
      - name: Step 2 - Run Enhanced Two-Stage Analysis
        run: |
          echo "🚀 Running enhanced CipherB + VWMA analysis..."
          python src/enhanced_analyzer_15m.py
          
      - name: Log Analysis Results
        run: |
          echo "📊 Analysis completed at $(date '+%Y-%m-%d %H:%M:%S UTC')"
          if [ -f cache/pending_signals.db ]; then
            echo "📋 Pending signals database exists"
            sqlite3 cache/pending_signals.db "SELECT COUNT(*) as pending_count FROM pending_signals WHERE status='MONITORING';" || echo "No pending signals"
          fi
          
      - name: Upload Artifacts (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: enhanced-analysis-results
          path: |
            cache/
            logs/
          retention-days: 7
