name: BBW 1H Fresh Analysis

on:
  schedule:
    - cron: '2 * * * *'  # Every hour at 2 minutes past
  workflow_dispatch:

jobs:
  bbw-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run BBW 1H Analysis
      env:
        BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
        BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        BBW_TELEGRAM_CHAT_ID: ${{ secrets.BBW_TELEGRAM_CHAT_ID }}
      run: python src/analyzer_1h_fresh.py
